### ISSUE TITLE
solution_for_each_qid.json

### ISSUE THREAD

**Issue by billycz8** [codezakh/DataEnvGym#1]
I was running through the live code bench tasks and I found that "with open(
        "workspace/notebooks__013_get_ground_truth_solutions_for_lcb/solution_for_each_qid.json",
        "r",
    ) as f:" caused an error. I cannot find the source file for the solution, should we download it somewhere?
    
    https://vscode.dev/github/codezakh/dataenvgym/blob/master/src/dataenvgym/gym/tasks/code/livecodebench_task.py#L64

**Comment by codezakh** [comment]
I just added a HF download for the solutions file, it should run automatically now. Let me know if it still doesn't work.

**Comment by billycz8** [comment]
Thanks!
