### ISSUE TITLE
The code files in the /examples/gqa directory are empty files

### ISSUE THREAD

**Issue by lizouss** [codezakh/DataEnvGym#2]
Your work is wonderful and captures my attention. However, I noticed that open_ended.py, skill_list.py, skill_tree.py in path/examples/gqa in your codebase are empty files, while the files in math and livecodebench are normal. Can you please fill the empty files so that I can run the example gqa dataset.

**Comment by codezakh** [comment]
Sorry about that! I filled in the example for GQA open-ended, will fill in the other ones in a bit!

**Comment by lizouss** [comment]
thank you～
