### ISSUE TITLE
MATH dataset used

### ISSUE THREAD

**Issue by billycz8** [codezakh/DataEnvGym#3]
Hello, I was working through the code and found that the MAThtask loads the dataset from lighteval/MATH from HuggingFace. However in the paper itself, the MATH dataset used was MATH (Hendrycks et al., 2021). I wanted to know for the test and results which dataset was used to obtain the 15.78 before teaching (I assume the two datasets are different unless I misunderstood). Thanks!

**Comment by codezakh** [comment]
The datasets are identical, the lighteval one is the MATH dataset from Hendrycks just hosted on HuggingFace

**Comment by billycz8** [comment]
So the dataset used for test is lighteval/MATH? and the MATH-hard was not used. Thanks!
